export const GET_ARTICLES =  'GET_ARTICLES';
export const GET_ARTICLES_BY_USER =  'GET_ARTICLES_BY_USER';
export const GET_ARTICLES_BY_ID =  'GET_ARTICLES_BY_ID';
export const ADD_ARTICLE =  'ADD_ARTICLE';
export const DELETE_ARTICLE =  'DELETE_ARTICLE';
export const GET_ERRORS =  'GET_ERRORS';
export const CREATE_MESSAGE =  'CREATE_MESSAGE';

export const USER_LOADING =  'USER_LOADING';
export const USER_LOADED =  'USER_LOADED';
export const AUTH_ERROR =  'AUTH_ERROR';

export const LOGIN_SUCCESS =  'LOGIN_SUCCESS';
export const LOGIN_FAIL =  'LOGIN_FAIL';

export const REGISTER_SUCCESS =  'REGISTER_SUCCESS';
export const REGISTER_FAIL =  'REGISTER_FAIL';

export const LOGOUT_SUCCESS =  'LOGOUT_SUCCESS';

export const MY_POSTS =  'MY_POSTS';


export const GET_CATEGORIES =  'GET_CATEGORIES';
export const GET_CATEGORY_ARTICLES =  'GET_CATEGORY_ARTICLES';
